version: '3'
services:
    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin
        restart: always
        ports:
            - 9411:9411
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        restart: always
        command:
            - --enable-feature=exemplar-storage
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - 9090:9090
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        volumes:
            - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
            - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
        ports:
            - 3000:3000
# Grafana creds: admin:admin

