global:
    scrape_interval: 2s
    evaluation_interval: 2s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
    - job_name: 'eureka'
    #   scheme: 'https'
      metrics_path: '/actuator/prometheus'
      eureka_sd_configs:
          - server: http://host.docker.internal:8761/eureka
